CREATE TABLE IF NOT EXISTS pojmy (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pojem TEXT NOT NULL,
    definice TEXT NOT NULL
);

INSERT INTO pojmy (pojem, definice) VALUES 
("DNS", "Systém překladu doménových jmen na IP adresy."),
("DHCP", "Protokol pro automatické přidělování IP adres v síti."),
("Docker", "Platforma pro spouštění aplikací v kontejnerech."),
("HTTP", "Protokol pro přenos dat na webu."),
("IP adresa", "Unikátní číslo identifikující zařízení v síti."),
("TCP", "Spolehlivý protokol pro přenos dat po síti."),
("UDP", "Rychlý protokol pro přenos dat bez záruky doručení."),
("FTP", "Protokol pro přenos souborů mezi počítači."),
("SSH", "Šifrovaný protokol pro vzdálený přístup k serveru."),
("SSL", "Protokol pro šifrování komunikace na internetu."),
("TLS", "Nástupce SSL pro bezpečnou komunikaci."),
("VPN", "Virtuální privátní síť pro šifrované připojení."),
("NAT", "Překlad síťových adres mezi privátní a veřejnou sítí."),
("MAC adresa", "Fyzická adresa síťového zařízení."),
("OSI model", "Referenční model rozdělující síťovou komunikaci do 7 vrstev."),
("Router", "Zařízení směrující datové pakety mezi sítěmi."),
("Switch", "Zařízení propojující zařízení v lokální síti."),
("Hub", "Zastaralé síťové zařízení vysílající data všem připojeným zařízením."),
("Firewall", "Síťové zařízení nebo software filtrující síťový provoz."),
("Proxy", "Prostředník mezi klientem a serverem v síti."),
("Load balancer", "Zařízení nebo software rozdělující zátěž mezi více serverů."),
("CDN", "Síť serverů distribuující obsah uživatelům co nejblíže."),
("API", "Rozhraní pro komunikaci mezi softwarovými aplikacemi."),
("REST", "Architektonický styl pro návrh webových API."),
("JSON", "Textový formát pro výměnu dat mezi aplikacemi."),
("XML", "Značkovací jazyk pro strukturovaný přenos dat."),
("YAML", "Čitelný formát pro konfigurační soubory."),
("Git", "Distribuovaný systém pro správu verzí kódu."),
("GitHub", "Webová platforma pro hostování Git repozitářů."),
("CI/CD", "Automatizovaný proces integrace a nasazování kódu."),
("Kubernetes", "Systém pro orchestraci kontejnerů ve velkém měřítku."),
("Linux", "Open-source operační systém používaný na serverech."),
("Windows Server", "Serverový operační systém od Microsoftu."),
("Ubuntu", "Populární linuxová distribuce vhodná pro servery."),
("Bash", "Příkazový interpret používaný v Linuxu."),
("PowerShell", "Příkazový interpret a skriptovací jazyk od Microsoftu."),
("Python", "Populární programovací jazyk pro skripty a webové aplikace."),
("Java", "Objektově orientovaný programovací jazyk platformově nezávislý."),
("JavaScript", "Skriptovací jazyk pro webové aplikace běžící v prohlížeči."),
("PHP", "Serverový skriptovací jazyk pro tvorbu webových stránek."),
("SQL", "Jazyk pro správu a dotazování relačních databází."),
("MySQL", "Populární open-source relační databázový systém."),
("PostgreSQL", "Výkonný open-source objektově-relační databázový systém."),
("SQLite", "Lehká vestavěná relační databáze uložená v jednom souboru."),
("MongoDB", "NoSQL databáze ukládající data ve formátu dokumentů."),
("Redis", "Rychlá in-memory databáze pro cache a fronty zpráv."),
("Nginx", "Výkonný webový server a reverzní proxy."),
("Apache", "Populární open-source webový server."),
("Flask", "Lehký webový framework pro Python."),
("Django", "Plnohodnotný webový framework pro Python."),
("Node.js", "Běhové prostředí pro JavaScript na straně serveru."),
("React", "JavaScriptová knihovna pro tvorbu uživatelských rozhraní."),
("HTML", "Značkovací jazyk pro strukturu webových stránek."),
("CSS", "Jazyk pro stylování webových stránek."),
("IPv4", "Čtvrtá verze internetového protokolu s 32bitovou adresou."),
("IPv6", "Šestá verze internetového protokolu s 128bitovou adresou."),
("Subnet maska", "Číslo určující hranici mezi síťovou a hostitelskou částí IP adresy."),
("Gateway", "Výchozí brána pro komunikaci mimo lokální síť."),
("VLAN", "Virtuální lokální síť oddělující provoz na fyzickém přepínači."),
("ICMP", "Protokol pro diagnostické zprávy v síti, např. ping."),
("ARP", "Protokol mapující IP adresy na MAC adresy v lokální síti."),
("BGP", "Protokol pro směrování mezi autonomními systémy na internetu."),
("OSPF", "Protokol pro dynamické směrování uvnitř autonomního systému."),
("SMTP", "Protokol pro odesílání e-mailů."),
("IMAP", "Protokol pro příjem a správu e-mailů na serveru."),
("POP3", "Protokol pro stahování e-mailů ze serveru."),
("HTTPS", "Zabezpečená verze HTTP šifrovaná pomocí TLS."),
("Port", "Číslo identifikující konkrétní službu nebo aplikaci na zařízení."),
("Socket", "Kombinace IP adresy a portu pro síťovou komunikaci."),
("Packet", "Jednotka dat přenášená po síti."),
("Bandwidth", "Maximální přenosová kapacita síťového spojení."),
("Latence", "Zpoždění při přenosu dat v síti."),
("Throughput", "Skutečná rychlost přenosu dat v síti."),
("Virtualizace", "Technologie umožňující spuštění více OS na jednom fyzickém serveru."),
("VMware", "Populární platforma pro virtualizaci serverů."),
("VirtualBox", "Bezplatný nástroj pro virtualizaci od Oracle."),
("Hypervisor", "Software umožňující provoz virtuálních strojů."),
("Cloud computing", "Poskytování IT služeb přes internet na vyžádání."),
("AWS", "Amazon Web Services, největší poskytovatel cloudových služeb."),
("Azure", "Cloudová platforma od Microsoftu."),
("Google Cloud", "Cloudová platforma od Googlu."),
("SaaS", "Software jako služba poskytovaná přes internet."),
("IaaS", "Infrastruktura jako služba v cloudu."),
("PaaS", "Platforma jako služba pro vývoj aplikací v cloudu."),
("Backup", "Záloha dat pro případ ztráty nebo poškození."),
("RAID", "Technologie pro redundantní ukládání dat na více discích."),
("SAN", "Síť pro vysokorychlostní přístup k úložištím."),
("NAS", "Síťové úložiště pro sdílení souborů v lokální síti."),
("Active Directory", "Adresářová služba Microsoftu pro správu uživatelů a počítačů."),
("LDAP", "Protokol pro přístup k adresářovým službám."),
("Kerberos", "Protokol pro síťovou autentizaci pomocí lístků."),
("OAuth", "Otevřený standard pro autorizaci přístupu k aplikacím."),
("JWT", "JSON Web Token pro bezpečný přenos informací mezi stranami."),
("Šifrování", "Proces převodu dat do nečitelné podoby pro ochranu."),
("Hashing", "Jednosměrná funkce převádějící data na otisk pevné délky."),
("Certifikát", "Digitální dokument ověřující identitu serveru nebo osoby."),
("PKI", "Infrastruktura veřejných klíčů pro správu digitálních certifikátů."),
("Malware", "Škodlivý software navržený k poškození nebo krádeži dat."),
("Ransomware", "Malware šifrující data a požadující výkupné."),
("Phishing", "Podvodný útok napodobující důvěryhodné subjekty."),
("DDoS", "Útok přetížením serveru velkým množstitvím požadavků."),
("Penetrační test", "Autorizovaný útok na systém za účelem nalezení zranitelností."),
("Zero-day", "Zranitelnost v software dosud neznámá výrobci."),
("Patch", "Opravná aktualizace software nebo operačního systému."),
("Antivirus", "Software chránící před škodlivými programy."),
("IDS", "Systém detekce průniků do sítě nebo systému."),
("IPS", "Systém prevence průniků blokující hrozby v reálném čase."),
("SIEM", "Systém pro sběr a analýzu bezpečnostních událostí."),
("SOC", "Bezpečnostní operační centrum monitorující IT infrastrukturu."),
("DevOps", "Kultura a praxe spojující vývoj a provoz IT."),
("Agile", "Iterativní metodika vývoje software."),
("Scrum", "Framework pro agilní řízení projektů."),
("Microservices", "Architektura rozdělující aplikaci na malé nezávislé služby."),
("Monolith", "Architektura kde je celá aplikace jedním celkem."),
("Serverless", "Model kde cloud automaticky spravuje servery za vývojáře."),
("Lambda", "Serverless výpočetní služba od AWS."),
("Terraform", "Nástroj pro správu infrastruktury jako kódu."),
("Ansible", "Nástroj pro automatizaci konfigurace serverů."),
("Puppet", "Nástroj pro automatizované řízení konfigurace systémů."),
("Chef", "Nástroj pro automatizaci infrastruktury a konfigurace."),
("Prometheus", "Open-source systém pro monitorování a alerting."),
("Grafana", "Platforma pro vizualizaci metrik a monitorovacích dat."),
("ELK Stack", "Sada nástrojů Elasticsearch, Logstash a Kibana pro analýzu logů."),
("Elasticsearch", "Distribuovaný vyhledávací a analytický engine."),
("Logstash", "Nástroj pro sběr a zpracování logů."),
("Kibana", "Vizualizační nástroj pro data v Elasticsearch."),
("RabbitMQ", "Open-source broker zpráv pro asynchronní komunikaci."),
("Kafka", "Distribuovaná platforma pro streamování událostí."),
("WebSocket", "Protokol pro obousměrnou komunikaci v reálném čase."),
("gRPC", "Moderní framework pro vzdálené volání procedur od Googlu."),
("GraphQL", "Dotazovací jazyk pro API s flexibilním získáváním dat."),
("Webhook", "HTTP callback zasílaný automaticky při určité události."),
("Cron", "Plánovač úloh v Linuxu pro opakované spouštění příkazů."),
("Systemd", "Systém pro správu služeb a procesů v Linuxu."),
("UFW", "Jednoduchý nástroj pro správu firewallu v Ubuntu."),
("iptables", "Nástroj pro konfiguraci síťového firewallu v Linuxu."),
("Wireshark", "Nástroj pro zachytávání a analýzu síťového provozu."),
("Nmap", "Nástroj pro skenování sítí a zjišťování otevřených portů."),
("Curl", "Příkazový nástroj pro přenos dat přes různé protokoly."),
("Wget", "Nástroj pro stahování souborů z internetu přes příkazovou řádku."),
("Ping", "Příkaz testující dostupnost zařízení v síti pomocí ICMP."),
("Traceroute", "Příkaz zobrazující cestu paketu sítí k cíli."),
("Netstat", "Příkaz zobrazující síťová připojení a statistiky."),
("ifconfig", "Příkaz pro zobrazení a konfiguraci síťových rozhraní v Linuxu."),
("ip route", "Příkaz pro správu směrovacích tabulek v Linuxu."),
("chmod", "Příkaz pro změnu oprávnění souborů v Linuxu."),
("chown", "Příkaz pro změnu vlastníka souboru v Linuxu."),
("grep", "Příkaz pro vyhledávání vzorů v textu v Linuxu."),
("awk", "Nástroj pro zpracování a analýzu textových souborů v Linuxu."),
("sed", "Proudový editor pro transformaci textu v Linuxu."),
("tar", "Nástroj pro archivaci a kompresi souborů v Linuxu."),
("rsync", "Nástroj pro efektivní synchronizaci souborů a zálohování."),
("Vim", "Textový editor pro příkazovou řádku v Linuxu."),
("Nano", "Jednoduchý textový editor pro příkazovou řádku."),
("tmux", "Terminálový multiplexer umožňující více relací v jednom okně."),
("Screen", "Nástroj pro správu více terminálových relací najednou."),
("LVM", "Správce logických svazků pro flexibilní správu diskového prostoru."),
("ext4", "Populární linuxový souborový systém čtvrtá generace."),
("NTFS", "Souborový systém používaný ve Windows."),
("FAT32", "Starší souborový systém kompatibilní s mnoha zařízeními."),
("Swap", "Odkládací prostor na disku používaný jako rozšíření RAM."),
("RAM", "Operační paměť počítače pro dočasné ukládání dat."),
("CPU", "Centrální procesorová jednotka vykonávající instrukce programu."),
("GPU", "Grafická procesorová jednotka pro paralelní výpočty."),
("SSD", "Rychlé úložiště dat bez pohyblivých částí."),
("HDD", "Tradiční pevný disk s magnetickými plotnami."),
("BIOS", "Firmware inicializující hardware počítače při startu."),
("UEFI", "Moderní náhrada BIOS s grafickým rozhraním."),
("Bootloader", "Program načítající operační systém při startu počítače."),
("GRUB", "Populární bootloader pro Linux."),
("Kernel", "Jádro operačního systému spravující hardware a procesy."),
("Process", "Spuštěný program s vlastním adresovým prostorem v paměti."),
("Thread", "Vlákno provádění v rámci jednoho procesu."),
("Mutex", "Synchronizační mechanismus zabraňující souběžnému přístupu ke zdroji."),
("Deadlock", "Situace kdy dva procesy čekají na zdroje navzájem blokované."),
("Stack", "Datová struktura pracující na principu LIFO."),
("Queue", "Datová struktura pracující na principu FIFO."),
("OOP", "Paradigma programování založené na objektech a třídách."),
("Třída", "Šablona definující vlastnosti a metody objektů v OOP."),
("Dědičnost", "Mechanismus OOP umožňující třídě přebírat vlastnosti jiné třídy."),
("Polymorfismus", "Schopnost OOP objektů reagovat různě na stejnou zprávu."),
("API endpoint", "Konkrétní URL adresa kde API přijímá požadavky."),
("HTTP status kód", "Číselný kód vyjadřující výsledek HTTP požadavku."),
("200 OK", "HTTP kód indikující úspěšné zpracování požadavku."),
("404 Not Found", "HTTP kód indikující nenalezení požadovaného zdroje."),
("500 Internal Server Error", "HTTP kód indikující chybu na straně serveru."),
("301 Redirect", "HTTP kód pro trvalé přesměrování na novou URL."),
("CORS", "Mechanismus povolující požadavky mezi různými doménami."),
("Cookie", "Malý datový soubor ukládaný prohlížečem pro sledování stavu."),
("Session", "Dočasné uložení stavu uživatele na straně serveru."),
("Token", "Řetězec použitý pro autentizaci nebo autorizaci."),
("Base64", "Kódování binárních dat do textové podoby."),
("Regex", "Vzor pro vyhledávání a manipulaci s textem."),
("IDE", "Integrované vývojové prostředí pro psaní kódu."),
("Debugger", "Nástroj pro hledání a opravu chyb v kódu."),
("Compiler", "Program překládající zdrojový kód do strojového jazyka."),
("Interpreter", "Program vykonávající zdrojový kód řádek po řádku."),
("Virtuální stroj", "Softwarová emulace fyzického počítače."),
("Kontejner", "Izolované prostředí pro spouštění aplikací sdílející jádro OS."),
("Image", "Šablona pro vytvoření Docker kontejneru."),
("Registry", "Úložiště Docker images, např. Docker Hub."),
("Volume", "Trvalé úložiště dat pro Docker kontejnery."),
("Environment variable", "Proměnná prostředí předávající konfiguraci aplikaci."),
("Makefile", "Soubor definující příkazy pro automatizaci sestavení projektu."),
("Dependency", "Externě závislá knihovna nebo balíček potřebný pro aplikaci."),
("Package manager", "Nástroj pro správu softwarových balíčků a závislostí."),
("npm", "Správce balíčků pro JavaScript a Node.js."),
("pip", "Správce balíčků pro Python."),
("apt", "Správce balíčků pro Debian a Ubuntu Linux."),
("yum", "Správce balíčků pro Red Hat a CentOS Linux."),
("Ollama", "Nástroj pro lokální spouštění velkých jazykových modelů na CPU."),
("LLM", "Velký jazykový model trénovaný na rozsáhlých textových datech."),
("AI", "Umělá inteligence simulující lidské myšlení a rozhodování."),
("Machine learning", "Odvětví AI kde se modely učí ze vzorů v datech."),
("Neural network", "Výpočetní model inspirovaný strukturou lidského mozku."),
("Prompt", "Vstupní text zadávaný jazykovému modelu pro generování odpovědi."),
("Token (AI)", "Základní jednotka textu zpracovávaná jazykovým modelem."),
("Fine-tuning", "Doladění předtrénovaného modelu na specifická data."),
("Inference", "Proces generování výstupu z natrénovaného modelu."),
("Model", "Matematická reprezentace naučených vzorů z trénovacích dat.");